# Generated by Django 3.0.2 on 2020-01-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.CharField(default='', max_length=20, verbose_name='Цена'),
        ),
    ]
