# Generated by Django 3.0.2 on 2020-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200117_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='sort',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок'),
        ),
    ]
