# Generated by Django 3.0.2 on 2020-01-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_model1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=120, verbose_name='Названи услуги')),
                ('slug1', models.SlugField(default='', max_length=120, unique=True, verbose_name='URL')),
                ('text1', models.TextField(default='', verbose_name='Тест модели')),
                ('header1', models.CharField(blank=True, max_length=120, null=True, verbose_name='аголовок')),
                ('sub_header1', models.CharField(blank=True, max_length=200, null=True, verbose_name='одзаголовок')),
                ('images1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Катинка чего-либо')),
                ('active1', models.BooleanField(default=True, verbose_name='публиковать')),
                ('title1', models.CharField(max_length=120, verbose_name='Tite')),
                ('description1', models.CharField(max_length=250, verbose_name='escription')),
                ('keywords1', models.CharField(max_length=250, verbose_name='Kewords')),
                ('sort1', models.PositiveIntegerField(default=0, unique=True, verbose_name='орядок')),
                ('price1', models.CharField(default='', max_length=20, verbose_name='Цеа')),
                ('bid', models.CharField(max_length=5, verbose_name='Bid')),
            ],
            options={
                'verbose_name': 'Мод',
                'verbose_name_plural': 'Модs',
            },
        ),
        migrations.DeleteModel(
            name='Model1',
        ),
    ]
